// const puppeteer = require("puppeteer");
// const userAgent = require("user-agents");
// const Questions = require("./Models/questions");

// const jobTitles = [
//   // "Account Manager",
//   // "Account Officer",
//   // "Account Representative",
//   // "Accountant",
//   // "Accounting Assistant",
//   // "Accounting Clerk",
//   // "Accounting Manager",
//   // "Accounts Assistant",
//   // "Accounts Payable Specialist",
//   // "Accounts Receivable Specialist",
//   // "Active Directory",
//   // "Actuary",
//   // "Administrative Assistant",
//   // "Administrative Clerk",
//   // "Administrative Manager",
//   // "Administrative Officer",
//   // "Administrator",
//   // "Advertising Manager",
//   // "Agile",
//   // "Analyst",
//   // "Analytical",
//   // "Anesthesiologist",
//   // "Architect",
//   // "Area Manager",
//   // "Art Director",
//   // "Assembler",
//   // "Assistant Accountant",
//   // "Assistant Administrator",
//   // "Assistant Controller",
//   // "Assistant Manager",
//   // "Assistant Project Manager",
//   // "Assistant Property Manager",
//   // "Assistant Store Manager",
//   // "Assistant Teacher",
//   // "Athletic Trainer",
//   // "Attention to Detail",
//   // "Attorney",
//   // "Audiologist",
//   // "Auditor",
//   // "Auto Mechanic",
//   // "Automotive Technician",
//   // "Babysitter",
//   // "Baker",
//   // "Bank Teller",
//   // "Banker",
//   // "Banquet Server",
//   // "Bar Manager",
//   // "Barista",
//   // "Bartender",
//   // "Benefits Coordinator",
//   // "Big Data",
//   // "Billing Clerk",
//   // "Billing Specialist",
//   // "Biomedical Engineer",
//   // "Bookkeeper",
//   // "Branch Manager",
//   // "Brand Ambassador",
//   // "Brand Manager",
//   // "Budgeting",
//   // "Building Maintenance Technician",
//   // "Busboy",
//   // "Business Administrator",
//   // "Business Analyst",
//   // "Business Consultant",
//   // "Business Developer",
//   // "Business Development Executive",
//   // "Business Development Manager",
//   // "Business Development Officer",
//   // "Business Intelligence Analyst",
//   // "Business Manager",
//   // "Business Systems Analyst",
//   // "Buyer",
//   // "csharp",
//   // "cplusplus",
//   // "Call Center Manager",
//   // "Call Center Representative",
//   // "Camp Counselor",
//   // "Car Salesperson",
//   // "Care Assistant",
//   // "Caregiver",
//   // "Carpenter",
//   // "Case Manager",
//   // "Caseworker",
//   // "Cashier",
//   // "Caterer",
//   // "CEO Chief Executive Officer",
//   // "CFO Chief Financial Officer",
//   // "Charge Nurse",
//   // "Chef",
//   // "Chemical Engineer",
//   // "Chief Marketing Officer",
//   // "Chief Medical Officer",
//   // "Chief of Staff",
//   // "Chief Operating Officer",
//   // "Child Care Worker",
//   // "CIO Chief Information Officer",
//   // "Civil Engineer",
//   // "Cleaner",
//   // "Clerk",
//   // "Client Services Manager",
//   // "Clinical Psychologist",
//   // "Cna Certified Nursing Assistant",
//   // "CNC Operator",
//   // "Collections Specialist",
//   // "Collector",
//   // "Commercial Manager",
//   // "communication skills",
//   // "Communications Manager",
//   // "Communications Officer",
//   // "Community Manager",
//   // "Compliance Manager",
//   // "Computer Engineer",
//   // "Computer Operator",
//   // "Computer Programmer",
//   // "Computer Technician",
//   // "Concierge",
//   // "Conflict Management",
//   // "Construction Manager",
//   // "Construction Project Manager",
//   // "Construction Superintendent",
//   // "Construction Worker",
//   // "Consultant",
//   // "Contact Tracer",
//   // "Content Manager",
//   // "Content Writer",
//   // "Contract Administrator",
//   // "Contract Manager",
//   // "Controller",
//   // "COO Chief Operating Officer",
//   // "Cook",
//   // "Coordinator",
//   // "Copywriter",
//   // "Correctional Officer",
//   // "Cosmetologist",
//   // "Cost Accountant",
//   // "Counselor",
//   // "Cpa Certified Public Accountant",
//   // "Creative Director",
//   // "Creativity",
//   // "Credit Analyst",
//   // "Credit Controller",
//   // "Crew Member",
//   // "Critical Thinking",
//   // "CSS",
//   // "CTO Chief Technology Officer",
//   // "Custodian",
//   // "Customer Service Associate",
//   // "Customer Service Manager",
//   // "Customer Service Representative",
//   // "Data Analyst",
//   // "Data Architect",
//   // "Data Entry Clerk",
//   // "Data Manager",
//   // "Data Scientist",
//   // "Database Administrator",
//   // "Debt Collector",
//   // "Decision Making",
//   // "Delivery Driver",
//   // "Dental Assistant",
//   // "Dental Hygienist",
//   // "Dental Office Manager",
//   // "Dentist",
//   // "Dermatologist",
//   // "Design Engineer",
//   // "Desktop Support Specialist",
//   // "Development Director",
//   // "Diesel Mechanic",
//   // "Dietary Aide",
//   // "Dietitian",
//   // "Digital Marketing Manager",
//   // "Direct Support Professional",
//   // "Director of Finance",
//   // "Director Of Marketing",
//   // "Director of Nursing",
//   // "Director of Operations",
//   // "Director Of Sales",
//   // "Dishwasher",
//   // "Dispatcher",
//   // "District Manager",
//   // "Doctor",
//   // "Document Controller",
//   // "Driver",
//   // "Electrical Engineer",
//   // "Electrician",
//   // "Electronics Engineer",
//   // "Emotional Intelligence",
//   // "Engineer",
//   // "Enterprise Architect",
//   // "ER Nurse",
//   // "Esthetician",
//   // "Estimator",
//   // "Event Coordinator",
//   // "Event Planner",
//   // "Excel",
//   // "Executive Assistant",
//   // "Executive Chef",
//   // "Executive Director",
//   // "Executive Secretary",
//   // "Expeditor",
//   // "Facilities Manager",
//   // "File Clerk",
//   // "Finance Manager",
//   // "Financial Advisor",
//   // "Financial Analyst",
//   // "Financial Controller",
//   // "Financial Manager",
//   // "Financial Planner",
//   // "Firefighter",
//   // "Fleet Manager",
//   // "Flight Attendant",
//   // "Food Runner",
//   // "Food Server",
//   // "Forklift Operator",
//   // "Front Desk Agent",
//   // "Front End Developer",
//   // "General Counsel",
//   // "General Manager",
//   // "Graphic Designer",
//   // "Groundskeeper",
//   // "Guidance Counselor",
//   // "Hair Stylist",
//   // "Handyman",
//   // "Head Cashier",
//   // "Health Administrator",
//   // "Help Desk Clerk",
//   // "Home Health Aide",
//   // "Home Health Nurse",
//   // "Hostess",
//   // "Hotel Front Desk Clerk",
//   // "Hotel Manager",
//   // "Housekeeper",
//   // "HR Assistant",
//   // "HR Director",
//   // "HR Generalist",
//   // "HR Manager",
//   // "HTML",
//   // "Human Resources Manager",
//   // "Industrial Engineer",
//   // "Inside Sales Representative",
//   // "Insurance Agent",
//   // "Integrity",
//   // "Interior Designer",
//   // "Intern",
//   // "Internal Auditor",
//   // "Interpersonal Skills",
//   // "Inventory Clerk",
//   // "Inventory Manager",
//   // "Inventory Specialist",
//   // "IT Business Analyst",
//   // "IT Director",
//   // "IT Manager",
//   // "It Project Manager",
//   // "IT Specialist",
//   // "IT Technician",
//   // "Janitor",
//   // "Java",
//   // "Javascript",
//   // "Junior Accountant",
//   // "Kindergarten Teacher",
//   // "Kitchen Manager",
//   // "Lab Assistant",
//   // "Lab Technician",
//   // "Laborer",
//   // "Law Clerk",
//   // "Lawyer",
//   // "Lead Teacher",
//   // "Leadership",
//   // "Leasing Agent",
//   // "Leasing Consultant",
//   // "Legal Assistant",
//   // "Legal Secretary",
//   // "Librarian",
//   // "Licensed Practical Nurse Lpn",
//   // "Lifeguard",
//   // "Line Cook",
//   // "Loan Officer",
//   // "Loan Processor",
//   // "Logistics Coordinator",
//   // "Logistics Manager",
//   // "Logistics Specialist Coordinator",
//   // "Machine Operator",
//   // "Maintenance Manager",
//   // "Maintenance Technician",
//   // "Management Assistant",
//   // "Manager",
//   // "Manufacturing Engineer",
//   // "Marketer",
//   // "Marketing",
//   // "Marketing Assistant",
//   // "Marketing Coordinator",
//   // "Marketing Director",
//   // "Marketing Intern",
//   // "Marketing Manager",
//   // "Marketing Specialist",
//   // "Massage Therapist",
//   // "Material Handler",
//   // "Math",
//   // "Mechanic",
//   // "Mechanical Engineer",
//   // "Medical Assistant",
//   // "Medical Biller",
//   // "Medical Coder",
//   // "Medical Director",
//   // "Medical Office Assistant",
//   // "Medical Office Manager",
//   // "Medical Receptionist",
//   // "Medical Records Clerk",
//   // "Medical Scribe",
//   // "Medical Secretary",
//   // "Medical Technologist",
//   // "Merchandiser",
//   // "Millwright",
//   // "Neonatal Nurse",
//   // "Network Administrator",
//   // "Network Engineer",
//   // "Network Technician",
//   // "Neurologist",
//   // "Night Auditor",
//   // "Nurse",
//   // "Nurse Manager",
//   // "Nurse Practitioner",
//   // "Nursing Assistant",
//   // "Nutritionist",
//   // "Occupational Therapist",
//   // "Occupational Therapy Assistant",
//   // "Office Administrator",
//   // "Office Assistant",
//   // "Office Clerk",
//   // "Office Coordinator",
//   // "Office Manager",
//   // "Operational Manager",
//   // "Operations Analyst",
//   // "Operations Coordinator",
//   // "Operations Manager",
//   // "Optician",
//   // "Optometrist",
//   // "Organizational Skills",
//   // "Outside Sales Representative",
//   // "Painter",
//   // "Paralegal",
//   // "Paramedic",
//   // "Paraprofessional",
//   // "Pastry Chef",
//   // "Pathologist",
//   // "Patient Advocate",
//   // "Patient Care Technician",
//   // "Payroll Clerk",
//   // "Payroll Manager",
//   // "Payroll Specialist",
//   // "Pediatrician",
//   // "Personal Assistant",
//   // "Personal Banker",
//   // "Personal Trainer",
//   // "Pharmacist",
//   // "Pharmacy Technician",
//   // "Phlebotomist",
//   // "Photographer",
//   // "Physical Therapist",
//   // "Physical Therapist Assistant",
//   // "Physical Therapy Assistant",
//   // "Physician",
//   // "Physician Assistant",
//   // "Plant Manager",
//   // "Plumber",
//   // "Police",
//   // "Police Officer",
//   // "Porter",
//   // "Practice Manager",
//   // "Prep Cook",
//   // "Preschool Teacher",
//   // "President",
//   // "Principal",
//   // "Probation Officer",
//   // "Problem Solving",
//   // "Process Engineer",
//   // "Procurement Manager",
//   // "Producer",
//   // "Product Manager",
//   // "Product Marketing Manager",
//   // "Production Assistant",
//   // "Production Manager",
//   // "Production Supervisor",
//   // "Production Worker",
//   // "Program Analyst",
//   // "Program Assistant",
//   // "Program Coordinator",
//   // "Program Director",
//   // "Program Manager",
//   // "Programmer",
//   // "Programmer Analyst",
//   // "Project Coordinator",
//   // "Project Engineer",
//   // "Project Manager",
//   // "Property Manager",
//   // "Psychiatrist",
//   // "Psychologist",
//   // "Public Relations Account Manager",
//   // "Purchasing Agent",
//   // "Purchasing Assistant",
//   // "Purchasing Manager",
//   // "Python",
//   // "QA",
//   // "Quality Control Inspector",
//   // "Quality Engineer",
//   // "Quality Inspector",
//   // "Quality Manager",
//   // "R",
//   // "Radiologic Technologist",
//   // "Radiologist",
//   // "Real Estate Agent",
//   // "Real Estate Broker",
//   // "Realtor",
//   // "Receiving Clerk",
//   // "Receptionist",
//   // "Recruiter",
//   // "Regional Sales Manager",
//   // "registered nurse rn",
//   // "Resident Assistant",
//   // "Respiratory Therapist",
//   // "Restaurant Manager",
//   // "Restaurant Server",
//   // "Retail Assistant Manager",
//   // "Retail Associate",
//   // "Retail Sales Associate",
//   // "Retail Store Manager",
//   // "Safety Manager",
//   // "Sales",
//   // "Sales Assistant",
//   // "Sales Associate",
//   // "Sales Clerk",
//   // "Sales Consultant",
//   // "Sales Coordinator",
//   // "Sales Director",
//   // "Sales Engineer",
//   // "Sales Manager",
//   // "Sales Representative",
//   // "Sales Support Specialist",
//   // "Scheduler",
//   // "School Bus Driver",
//   // "School Social Worker",
//   // "Secretary",
//   // "Security",
//   // "Security Guard",
//   // "Security Officer",
//   // "Self-Starter",
//   // "Senior Accountant",
//   // "Senior Project Manager",
//   // "Server",
//   // "Service Advisor",
//   // "Service Manager",
//   // "Shift Leader",
//   // "Shift Manager",
//   // "Shipping Clerk",
//   // "Social Media Intern",
//   // "Social Media Manager",
//   // "Social Worker",
//   // "Software Architect",
//   // "Software Developer",
//   // "Software Engineer",
//   // "Sous Chef",
//   // "Special Education Teacher",
//   // "SQL",
//   // "Staff Accountant",
//   // "Statistics",
//   // "Stocker",
//   // "Store Associate",
//   // "Store Clerk",
//   // "Store Manager",
//   // "Strategic Thinking",
//   // "Substitute Teacher",
//   // "Supervisor",
//   // "Supply Chain Manager",
//   // "Surgeon",
//   // "Surgical Technician",
//   // "System Administrator",
//   // "System Engineer",
//   // "Systems Administrator",
//   // "Systems Analyst",
//   // "Systems Engineer",
//   // "Tableau",
//   // "Tax Preparer",
//   // "Teacher",
//   // "Teacher Assistant",
//   // "Teaching Assistant",
//   // "Team Leader",
//   // "Teamwork",
//   // "Technical Director",
//   // "Technical Support",
//   // "Technical Support Specialist",
//   "Technical Writer",
//   "Technician",
//   "Telemarketer",
//   "Teller",
//   "Time Management",
//   "Training Coordinator",
//   "Training Manager",
//   "Travel Agent",
//   "Treasurer",
//   "Troubleshooting",
//   "Truck Driver",
//   "Tutor",
//   "Ultrasound Technician",
//   "Underwriter",
//   "UX Designer",
//   "Veterinarian",
//   "Veterinary Assistant",
//   "Veterinary Technician",
//   "Waiter",
//   "Waitress",
//   "Warehouse Manager",
//   "Warehouse Worker",
//   "Web Designer",
//   "Web Developer",
//   "Welder",
//   "Work Ethic",
//   "Writer",
// ];

// function delay(ms) {
//   return new Promise((resolve) => setTimeout(resolve, ms));
// }

const fetchIndeed = async () => {
  // for (const job of jobTitles) {
  //   const browser = await puppeteer.launch({
  //     headless: true,
  //   });
  //   const context = await browser.createIncognitoBrowserContext();
  //   const page = await context.newPage();
  //   await page.setUserAgent(userAgent.random().toString());

  //   await page.setViewport({ width: 1366, height: 768 });
  //   await page.emulate(puppeteer.KnownDevices["iPhone 13 Pro"]);

  //   await page.setDefaultNavigationTimeout(0);
  //   const url = `https://www.indeed.com/hire/interview-questions/${job.replace(
  //     /\s/g,
  //     "-"
  //   )}?co=US`;

  //   await delay(Math.random() * 2000 + 1000);

  //   await page.goto(url, {
  //     waitUntil: "networkidle0",
  //   });

  //   await delay(Math.random() * 2000 + 1000);

  //   const questions = await page.evaluate(() => {
  //     let questionElements = Array.from(
  //       document.querySelectorAll("ol.list_of_questions li")
  //     );

  //     if (!questionElements || questionElements.length === 0) {
  //       questionElements = Array.from(
  //         document.querySelectorAll("div.qa-question h2")
  //       );
  //     }

  //     return questionElements.map((question) => {
  //       let questionText = question.innerText.trim().replace("See answer", "");
  //       const questionEndIndex = Math.max(
  //         questionText.lastIndexOf("?"),
  //         questionText.lastIndexOf(".")
  //       );
  //       if (questionEndIndex !== -1) {
  //         questionText = questionText.slice(0, questionEndIndex + 1);
  //       }
  //       return questionText;
  //     });
  //   });
  //   const question = new Questions({
  //     subject: job,
  //     questions,
  //     valid: true,
  //     url,
  //     userId: "",
  //   });
  //   await question.save();

  //   console.log(job);
  //   await browser.close();
  // }

};

module.exports = { fetchIndeed };
